export const ADMIN_ROUTE = '/admin'
export const MAIN_ROUTE = '/main'
export const LOGIN_ROUTE = '/auth'
export const REGISTRATION_ROUTE = '/auth'
export const SUBSCRIPTIONS_ROUTE = '/subscriptions'
export const TEMPLATES_ROUTE = '/templates'
